/**
 * @name synonymService
 *
 * @fileOverview
 * Angular service to match one noun (Wikidata entity label) to another, often more general one (Webhosting glyph icon term--from webhostinghub.com/glyphs/ -- requires html loading "whhg-font/css/whhg.css")
 *
 */

var synonymService = angular.module('synonymService', []);

synonymService.factory('SynonymService', function() {
    //format is label: synonym 
    //for example, to have the Wikidata label of "taxon" associated with the WHG image of "icon-butterfly", see the first row below
    var synList = {
    	"taxon" : "butterfly",
    	"dog breed" : "dog",
    	"breed" : "dog",
        "breed" : "dog",
        "rabbit breed" : "rabbit",
    	"ocean" : "wavealt-seaalt",
    	"state forest" : "forest-tree",
    	"state forest (wisconsin)" : "forest-tree",
    	"human" : "manalt",
    	"company" : "factory",
        "privately held company" : "store",
        "business enterprise" : "factory",
    	"names of the days of the week" : "calendar",
    	"economic bubble" : "moneybag",
    	"book" : "bookthree",
    	"letter" : "pen",
    	"film" : "film",
        "series of creative works" : "stacks",
        "extinct language" : "language",
        "language family" : "language",
    	"test automation framework" : "tools",
    	"good news" : "bookthree",
    	"mathematical constant" : "root",
    	"source code editor" : "html",
    	"html editor" : "html",
    	"free software" : "html",
    	"library" : "html",
    	"song" : "music",
    	"chorale" : "music",
    	"hymn" : "musicsheet",
    	"play" : "boardgame",
    	"tragedy" : "theather",
    	"art movement" : "palette-painting",
        "painting": "canvas",
        "group of paintings": "canvas",
    	"video game" : "gameboy",
    	"prison" : "lock",
    	"planet" : "planet",
    	"dwarf planet" : "planet",
    	"minor planet" : "planet",
    	"planemo" : "planet",
    	"extrasolar planet" : "planet",
        "multiple star" : "star",
        "binary star" : "star",
    	"chemical compound" : "beaker",
    	"diagnostic test" : "beaker",
    	"scientific journal" : "magazine",
    	"unit of time" : "clockalt-timealt",
    	"town" : "house",
    	"village" : "house",
    	"city" : "city",
        "human settlement" : "city",
        "human-geographic territorial entity" : "map-marker",
        "census designated place" : "map-marker",
    	"road" : "road",
    	"dog type" : "dog",
    	"hunting dog" : "dog",
    	"working dog" : "dog",
    	"mongrel" : "dog",
    	"football team" : "football-soccer",
    	"space shuttle" : "shuttle",
    	"newspaper" : "news",
    	"composition" : "music",
    	"star" : "constellation",
    	"hypothetical planet" : "planet",
    	"hypothesis" : "lightbulb-idea",
    	"continent" : "map-marker",
        "fictional continent" : "map-marker",
    	"forest" : "forest-tree",
    	"national historic landmark of the usa" : "map-marker",
    	"protected area" : "treethree",
    	"ecoregion" : "leaf",
    	"extinction event" : "fishbone",
    	"television program" : "tv",
        "television series" : "tv",
        "television" : "tv",
    	"mood" : "eye-open",
    	"emotion" : "eye-open",
    	"feeling" : "eye-open",
    	"programming language" : "debug",
    	"cereal" : "plantalt",
    	"automobile" : "automobile-car",
    	"tablet computer" : "tablet",
    	"ice cream" : "icecream",
    	"citrus" : "lemon",
    	"fertilizer" : "macro-plant",
    	"compost" : "plantalt",
    	"church" : "church",
    	"ancient city" : "house",
    	"university" : "student-school",
    	"catholic university" : "student-school",
    	"seminary" : "church",
    	"college" : "student-school",
    	"community college" : "student-school",
    	"computer program" : "software",
    	"color" : "colors",
    	"primary color" : "colors",
    	"factory" : "factory",
    	"u.s. state" : "map-marker",
    	"political catch phrase" : "quote",
    	"phrase" : "quote",
    	"sentence" : "featheralt-write",
    	"religious law" : "law",
    	"public holiday" : "calendar",
    	"organization" : "groups-friends",
    	"sea" : "wavealt-seaalt",
    	"body of water" : "wavealt-seaalt",
    	"infectious disease" : "danger",
    	"pathogen" : "danger",
    	"dog" : "dog",
    	"food" : "foodtray",
    	"website" : "websitealt",
    	"project" : "projectcompare",
    	"day" : "calendar",
    	"month" : "calendar",
    	"creative work" : "brush",
    	"intellectual work" : "bookthree",
    	"text editor" : "software",
    	"software" : "software",
    	"programming tool" : "software",
    	"musical work" : "music",
    	"work of art" : "brush",
    	"drama" : "theather",
    	"theater" : "theather",
    	"art" : "brush",
        "art museum": "brush",
        "art gallery": "brush",
        "children's museum": "palette-painting",
        "museum": "parthenon",
    	"unmanned aerial vehicle" : "planealt",
    	"airliner" : "plane",
    	"transport aircraft" : "plane",
    	"aircraft" : "plane",
    	"craft" : "tools",
        "unit of length" : "ruler",
    	"mode of transport" : "tools",
    	"machine" : "tools",
    	"tool" : "tools",
    	"artificial object" : "tools",
    	"physical object" : "triangle",
    	"number" : "root",
    	"mathematical object" : "root",
    	"concept" : "lightbulb-idea",
    	"electronic game" : "gameboy",
    	"game" : "boardgame",
    	"chemical substance" : "flaskfull",
        "enzyme" : "vial",
    	"academic journal" : "magazine",
    	"specialized periodical publication" : "magazine",
    	"periodical literature" : "magazine",
        "book series" : "book",
    	"sports team" : "football-soccer",
    	"reusable launch system" : "shuttle",
        "impact crater" : "meteor",
    	"publication" : "magazine",
    	"national register of historic places" : "map-marker",
    	"motor vehicle" : "automobile-car",
    	"full-size car" : "automobile-car",
    	"hybrid electric vehicle" : "automobile-car",
    	"sport utility vehicle" : "automobile-car",
    	"Internet tablet" : "tablet",
    	"ipad" : "tablet",
    	"frozen dessert" : "icecream",
    	"dessert" : "cupcake",
    	"dish" : "soup",
    	"home appliance" : "fridge",
    	"toilet" : "toiletpaper",
    	"ecology" : "leaf",
    	"agriculture" : "plantalt",
    	"place of worship" : "temple",
    	"private university" : "student-school",
    	"educational institution" : "student-school",
    	"font" : "font",
    	"typeface" : "font",
    	"engraving" : "papercutter",
    	"microcomputer" : "monitor",
    	"home computer" : "monitor",
    	"computer" : "monitor",
    	"personal computer" : "monitor",
    	"smartphone" : "iphone",
    	"holiday" : "calendar",
        "public holidays in the united states" : "calendar",
        "federal holidays in the united states" : "calendar",
    	"event" : "calendar",
        "palimpsest": "canvas",
        "supercomputer": "terminal",
        "supercontinent": "map-marker",
        "continental fragment": "map-marker",
        "highland": "mountains",
        "craton": "globe",
        "orbit": "moonorbit",
        "rare disease": "firstaid",
        "car model": "automobile-car",
        "official state car": "automobile-car",
        "mountain": "mountains",
        "volcano": "mountains",
        "mountain range": "mountains",
        "mountain pass": "mountains",
        "lake": "wave-sea",
        "glacial lake": "wave-sea",
        "rift lake": "wave-sea",
        "contract": "document",
        "water deity": "viking",
        "greek sea god": "greekcolumn",
        "mythical character": "greekcolumn",
        "human biblical character": "manalt",
        "tribes of israel": "davidstar",
        "religion": "temple",
        "monotheism": "temple",
        "monotheistic religion": "temple",
        "landform": "world",
        "music genre": "music",
        "musical form": "music",
        "prelude": "music",
        "band": "music",
        "musical composition": "musicsheet",
        "bach cantata": "musicsheet",
        "radio format": "radio",
        "live album": "album-cover",
        "album": "album-cover",
        "single": "music",
        "plucked string instrument": "guitar",
        "musical instrument": "guitar",
        "brass instrument": "trumpet",
        "horn": "trumpet",
        "woodwind instrument": "music",
        "double reed instrument": "music",
        "musical" : "music",
        "idiophone": "music",
        "recorder": "music",
        "chordophone": "guitar",
        "television film" : "tv",
        "episode" : "tv",
        "election day": "calendar",
        "trick-taking game": "clubs",
        "high school": "student-school",
        "private school": "student-school",
        "drink": "sodacup",
        "energy drink": "sodacup",
        "ethnic group": "groups-friends",
        "nonprofit organization": "groups-friends",
        "voluntary association": "groups-friends",
        "wikimedia portal": "webpage",
        "mythological serpent": "saurus",
        "fossil taxon":"saurus",
        "chasma":"map-marker",
        "board game": "boardgame",
        "video game genre": "joystickarcade",
        "coup d'état": "tank",
        "political crisis": "gavel",
        "convention": "featheralt-write",
        "constitutional convention": "featheralt-write",
        "constitutional law": "law",
        "costa v enel": "law",
        "political thought": "thinking",
        "government commission": "groups-friends",
        "pudding": "chef",
        "salad": "carrot",
        "snack cake": "cupcake",
        "olympic sport event": "stadium",
        "content management system": "indexmanager",
        "national museum": "greekcolumn",
        "food museum": "restaurantmenu",
        "amusement park": "freeway",
        "sports venue": "stadium",
        "airport": "plane",
        "amusement ride": "freeway",
        "common name": "butterfly",
        "unique identifier": "contact-businesscard",
        "financial market": "stocks",
        "painting series": "brush",
        "illuminated manuscript": "book",
        "sculpture": "greekcolumn",
        "state of the united states": "map-marker",
        "animated character": "mickeymouse",
        "fictional character": "tophat",
        "binary system": "planet",
        "hypothetical astronomical object": "planet",
        "minor planet group": "planet",
        "ring system": "planet",
        "substellar object": "planet",
        "periodic comet": "asteroid",
        "quadrangle": "map",
        "wikimedia list article": "list",
        "limb": "split",
        "fictional planets of the solar system": "planet",
        "political family": "treediagram",
        "photograph": "pictureframe",
        "botanical garden": "plantalt",
        "national historic site": "flag",
        "file format": "file",
        "wiki software": "software",
        "raster graphics editor": "images-gallery",
        "application": "programok",
        "server software": "software",
        "proprietary software": "software",
        "software house": "office-building",
        "web framework": "websitealt",
        "national olympic committee": "groups-friends",
        "summer olympic games": "medal",
        "periodic table": "beakeralt",
        "aspect of history": "history",
        "nuclear physics": "science-atom",
        "type of subatomic particle": "science-atom",
        "physical quantity": "ruler",
        "charge": "lightning",
        "wikimedia disambiguation page": "miniconfused",
        "disease": "hospital",
        "alternative medicine": "pill-antivirusalt",
        "color blindness": "eye-open",
        "group of humans": "groups-friends",
        "shop": "store",
        "musical notation": "musicsheet",
        "musical instrument part": "music",
        "hurdy gurdy": "piano",
        "pan flute": "music",
        "zither": "violin",
        "orchestra": "musicsheet",
        "test": "exposure",
        "test bench": "desklamp",
        "film festival": "film",
        "scientific method": "dna",
        "analogy": "projectcompare",
        "experiment": "beakeralt",
        "political party": "parthenon",
        "primary nutritional group": "molecule",
        "organism": "butterfly",
        "feeding behavior": "foodtray"
    }
    
    var factory = {};
    
    /**
     * @param {string} Wikidata label for which we're trying to find synonym--matching is NOT case sensitive
     * @return {string} the synonym, or "" (empty string) if a synonym wasn't found
     * @example
     * factory.getSynonym('event')               // 'calendar'
     * factory.getSynonym('eVenT')               // 'calendar'
     * factory.getSynonym('iShouldntExist')      // ''
     * factory.getSynonym('i shouldnt exist')    // ''
     * factory.getSynonym('place of worship')    // 'temple'
     * factory.getSynonym('u.s. state')          // 'map-marker'
     * factory.getSynonym('full-size car')       // 'automobile-car'
     */
    factory.getSynonym = function(label) {
        return synList[ label.toLowerCase() ] || "";
    }
    
    
    /**
     * @param {Array} array of Wikidata labels for which we're trying to find synonym--matching is NOT case sensitive
     * @return {string} the first synonym found, or "" (empty string) if a synonym wasn't found
     * @example
     * factory.getAnySynonym(['event'])                            // 'calendar'
     * factory.getAnySynonym(['iShouldntExist','eVenT'])           // 'calendar'
     * factory.getAnySynonym([])                                   // ''
     * factory.getAnySynonym(['i shouldnt exist'])                 // ''
     * factory.getAnySynonym(['place of worship', 'u.s. state'])   // 'temple'
     * factory.getAnySynonym(['full-size car', 'iShouldntExist'])  // 'automobile-car'
     */
    factory.getAnySynonym = function(labelArray) {
        var firstMatch = labelArray.find( function(eachLabel) {
            return synList[ eachLabel.toLowerCase() ];
        });
        return firstMatch ? synList[firstMatch.toLowerCase()] : "";
    }
    
    /**
     * @param {string} noun (like entity labels) to check if it's a match for a WHG icon word
     * @returns {boolean} 
     * @example
     * factory.isGlyphMatch('bug')                // true
     * factory.isGlyphMatch('iShouldntMatch')     // false
     */
    factory.isGlyphMatch = function (noun) {
        var checkNoun = noun.toLowerCase();
        return !!whhgIcons.find( function(eachIcon) {
            return eachIcon === checkNoun;
        });
    }
    
    /**
     * @param {Array } array of strings (nouns, like entity labels) to find is one's a match for a WHG icon word
     * @returns {string} first match, or ""
     * @example
     * factory.findGlyphMatch(['bug'])                           // 'bug'
     * factory.findGlyphMatch(['iShouldntMatch','aBacUs'])       // 'abacus'
     * factory.findGlyphMatch(['iShouldntMatch','me neither'])   // ""
     * factory.findGlyphMatch([])                                // ""
     */
    factory.findGlyphMatch = function (nounArray) {
        var foundNoun = nounArray.find( function(eachNoun) {
            return factory.isGlyphMatch(eachNoun);
        });
        return foundNoun ? foundNoun.toLowerCase() : "";
    }
    
    /**
     * combination of getAnySynonym and findGlyphMatch
     * @param {Array} array of strings like nouns we want glyph for
     * @returns {string} name of the class for the glyph to display as the default image, or ""
     */
    factory.findSynOrGlyphMatch = function (labelArray) {
        return factory.getAnySynonym(labelArray) || factory.findGlyphMatch(labelArray);
    }
    
    
var whhgIcons = ["aaabattery",
"abacus",
"accountfilter",
"acsource",
"addfriend",
"address",
"addshape",
"addtocart",
"addtolist",
"adjust",
"adobe",
"ads-bilboard",
"affiliate",
"ajax",
"alarm",
"alarmalt",
"album-cover",
"alertalt",
"alertpay",
"algorhythm",
"alienship",
"alienware",
"align-center",
"align-justify",
"align-left",
"align-right",
"alignbottomedge",
"alignhorizontalcenter",
"alignleftedge",
"alignrightedge",
"aligntopedge",
"alignverticalcenter",
"amd",
"analogdown",
"analogleft",
"analogright",
"analogup",
"analytics-piechart",
"analyticsalt-piechartalt",
"anchor-port",
"android",
"angrybirds",
"antenna",
"apache-feather",
"aperture",
"appointment-agenda",
"archive",
"arrow-down",
"arrow-left",
"arrow-right",
"arrow-up",
"asterisk",
"asteriskalt",
"at",
"atari",
"authentication-keyalt",
"automobile-car",
"autorespond",
"avatar",
"avataralt",
"avengers",
"awstats",
"axe",
"backup-vault",
"backupalt-vaultalt",
"backupwizard",
"backward",
"bag",
"baloon",
"ban-circle",
"banana",
"bandwidth",
"bank",
"barchart",
"barchartalt",
"barcode",
"basecamp",
"basketball",
"bat",
"batman",
"batteryaltcharging",
"batteryaltfull",
"batteryaltsixty",
"batteryaltthird",
"batterycharged",
"batterycharging",
"batteryeighty",
"batteryempty",
"batteryforty",
"batteryfull",
"batterysixty",
"batterytwenty",
"bed",
"beer",
"bell",
"bigger",
"bill",
"binary",
"binoculars-searchalt",
"birdhouse",
"birthday",
"bishop",
"blackberry",
"blankstare",
"blogger-blog",
"bluetooth",
"bluetoothconnected",
"boardgame",
"boat",
"bold",
"bomb",
"bone",
"book",
"bookmark",
"boombox",
"bottle",
"bow",
"bowling",
"bowlingpins",
"bowtie",
"boxtrapper-mousetrap",
"braces",
"braille0",
"braille1",
"braille2",
"braille3",
"braille4",
"braille5",
"braille6",
"braille7",
"braille8",
"braille9",
"braillea",
"brailleb",
"braillec",
"brailled",
"braillee",
"braillef",
"brailleg",
"brailleh",
"braillei",
"braillej",
"braillek",
"braillel",
"braillem",
"braillen",
"brailleo",
"braillep",
"brailleq",
"brailler",
"brailles",
"braillespace",
"braillet",
"brailleu",
"braillev",
"braillew",
"braillex",
"brailley",
"braillez",
"brain",
"bread",
"breakable",
"briefcase",
"briefcasethree",
"briefcasetwo",
"brightness",
"brightnessfull",
"brightnesshalf",
"broom",
"browser",
"brush",
"bucket",
"bug",
"bullhorn",
"bus",
"businesscardalt",
"buttona",
"buttonb",
"buttonx",
"buttony",
"cactus-desert",
"calculator",
"calculatoralt",
"calendar",
"calendaralt-cronjobs",
"camera",
"candle",
"candy",
"candycane",
"cannon",
"canvas",
"canvasrulers",
"capacitator",
"capslock",
"captainamerica",
"carrot",
"cashregister",
"cassette",
"cd-dvd",
"certificate",
"certificatealt",
"certificatethree",
"cgi",
"cgicenter",
"chair",
"chat",
"check",
"checkboxalt",
"checkin",
"checkinalt",
"chef",
"cherry",
"chevron-down",
"chevron-left",
"chevron-right",
"chevron-up",
"chevrons",
"chicken",
"chocolate",
"christiancross",
"christmastree",
"chrome",
"cigarette",
"circle-arrow-down",
"circle-arrow-left",
"circle-arrow-right",
"circle-arrow-up",
"circleadd",
"circledelete",
"circledown",
"circleleft",
"circleright",
"circleselect",
"circleselection",
"circleup",
"clearformatting",
"clipboard-paste",
"clockalt-timealt",
"closetab",
"closewindow",
"cloud",
"clouddownload",
"cloudhosting",
"cloudsync",
"cloudupload",
"clubs",
"cmd",
"cms",
"cmsmadesimple",
"codeigniter",
"coffee",
"coffeebean",
"cog",
"colocation",
"colocationalt",
"colors",
"comment",
"commentout",
"commentround",
"commentroundempty",
"commentroundtyping",
"commentroundtypingempty",
"commenttyping",
"compass",
"concretefive",
"contact-businesscard",
"controllernes",
"controllerps",
"controllersnes",
"controlpanel",
"controlpanelalt",
"cooling",
"coppermine",
"copy",
"copyright",
"coupon",
"cpanel",
"cplusplus",
"cpu-processor",
"cpualt-processoralt",
"crayon",
"createfile",
"createfolder",
"creativecommons",
"creditcard",
"cricket",
"croisant",
"crop",
"crown",
"csharp",
"cssthree",
"cup-coffeealt",
"cupcake",
"curling",
"cursor",
"cut-scissors",
"dagger",
"danger",
"dart",
"darthvader",
"database",
"databaseadd",
"databasedelete",
"davidstar",
"dcsource",
"dedicatedserver",
"deletefile",
"deletefolder",
"delicious",
"designcontest",
"desklamp",
"dialpad",
"diamond",
"diamonds",
"die-dice",
"diefive",
"diefour",
"dieone",
"diesix",
"diethree",
"dietwo",
"diode",
"director",
"diskspace",
"distributehorizontalcenters",
"distributeverticalcenters",
"divide",
"dna",
"dnszone",
"document",
"doghouse",
"dollar",
"dollaralt",
"dolphinsoftware",
"domain",
"domainaddon",
"domino",
"donut",
"downleft",
"download",
"download-alt",
"downright",
"draft",
"dreamweaver",
"dribbble",
"dropmenu",
"drupal",
"drwho",
"edit",
"editalt",
"egg",
"eightball",
"eject",
"elipse",
"emailalt",
"emailexport",
"emailforward",
"emailforwarders",
"emailimport",
"emailrefresh",
"emailtrace",
"emergency",
"emptycart",
"enter",
"envelope",
"equalizer",
"equalizeralt",
"equals",
"eraser",
"erroralt",
"euro",
"euroalt",
"evernote",
"exchange-currency",
"exclamation-sign",
"excludeshape",
"exit",
"explorerwindow",
"exportfile",
"exposure",
"extinguisher",
"eye-close",
"eye-open",
"eye-view",
"eyedropper",
"facebook",
"facebookalt",
"facetime-video",
"factory",
"fantastico",
"faq",
"fast-backward",
"fast-forward",
"fastdown",
"fastleft",
"fastright",
"fastup",
"favoritefile",
"favoritefolder",
"featheralt-write",
"fedora",
"fence",
"file",
"film",
"filmstrip",
"filter",
"finder",
"fire",
"firefox",
"firewall",
"firewire",
"firstaid",
"fish",
"fishbone",
"flag",
"flagalt",
"flagtriangle",
"flash",
"flashlight",
"flashplayer",
"flaskfull",
"flickr",
"flower",
"flowernew",
"folder-close",
"folder-open",
"foldertree",
"font",
"foodtray",
"football-soccer",
"forbiddenalt",
"forest-tree",
"forestalt-treealt",
"fork",
"forklift",
"form",
"forrst",
"fort",
"forward",
"fourohfour",
"foursquare",
"freeway",
"fridge",
"fries",
"ftp",
"ftpaccounts",
"ftpsession",
"fullscreen",
"gameboy",
"gamecursor",
"gasstation",
"gearfour",
"ghost",
"gift",
"github",
"glass",
"glasses",
"glassesalt",
"globe",
"globealt",
"glue",
"gmail",
"golf",
"googledrive",
"googleplus",
"googlewallet",
"gpsoff-gps",
"gpson",
"gpu-graphicscard",
"gradient",
"grails",
"greenlantern",
"greenlightbulb",
"grooveshark",
"groups-friends",
"guitar",
"halflife",
"halo",
"hamburger",
"hammer",
"hand-down",
"hand-left",
"hand-right",
"hand-up",
"handcuffs",
"handdrag",
"handtwofingers",
"hanger",
"happy",
"harrypotter",
"hdd",
"hdtv",
"headphones",
"headphonesalt",
"heart",
"heartempty-love",
"hearts",
"helicopter",
"hexagon-polygon",
"hockey",
"home",
"homealt",
"hospital",
"hotdog",
"hotlinkprotection",
"hourglassalt",
"html",
"htmlfive",
"hydrant",
"icecream",
"icecreamalt",
"illustrator",
"imac",
"images-gallery",
"importcontacts",
"importfile",
"inbox",
"inboxalt",
"incomingcall",
"indent-left",
"indent-right",
"indexmanager",
"infinity",
"info-sign",
"infographic",
"ink",
"inkpen",
"insertbarchart",
"insertpicture",
"insertpicturecenter",
"insertpictureleft",
"insertpictureright",
"insertpiechart",
"instagram",
"install",
"intel",
"intersection",
"intersectshape",
"invert",
"invoice",
"ipcontrol",
"iphone",
"ipod",
"ironman",
"islam",
"island",
"italic",
"jar",
"jason",
"java",
"joomla",
"joystickarcade",
"joystickatari",
"jquery",
"jqueryui",
"kerning",
"key",
"keyboard",
"keyboardalt",
"keyboarddelete",
"kidney",
"king",
"knife",
"knight",
"knob",
"lab-flask",
"lamp",
"lan",
"language",
"laptop",
"lasso",
"lastfm",
"laugh",
"law",
"layers",
"layersalt",
"leaf",
"leechprotect",
"legacyfilemanager",
"lego",
"lifeempty",
"lifefull",
"lifehacker",
"lifehalf",
"lifepreserver",
"lightbulb-idea",
"lighthouse",
"lightning",
"lightningalt",
"line",
"lineheight",
"link",
"linkalt",
"linkedin",
"linux",
"list",
"list-alt",
"liver",
"loading-hourglass",
"loadingalt",
"lock",
"lockalt-keyhole",
"lollypop",
"lungs",
"macpro",
"macro-plant",
"magazine",
"magento",
"magnet",
"mailbox",
"mailinglists",
"man-male",
"managedhosting",
"map",
"map-marker",
"marker",
"marvin",
"mastercard",
"maximize",
"medal",
"medalbronze",
"medalgold",
"medalsilver",
"mediarepeat",
"men",
"menu",
"merge",
"mergecells",
"mergeshapes",
"metro-subway",
"metronome",
"mickeymouse",
"microphone",
"microscope",
"microsd",
"microwave",
"mimetype",
"minimize",
"minus",
"minus-sign",
"missedcall",
"mobile",
"moleskine",
"money-cash",
"moneybag",
"monitor",
"monstersinc",
"moon-night",
"mouse",
"mousealt",
"move",
"movieclapper",
"moviereel",
"muffin",
"mug",
"mushroom",
"music",
"musicalt",
"mutealt",
"mxentry",
"mybb",
"myspace",
"mysql-dolphin",
"nail",
"navigation",
"network",
"networksignal",
"news",
"newtab",
"newwindow",
"next",
"nexus",
"nintendods",
"nodejs",
"notes",
"notificationbottom",
"notificationtop",
"nut",
"off",
"office-building",
"officechair",
"ok",
"ok-circle",
"ok-sign",
"oneup",
"oneupalt",
"opencart",
"opennewwindow",
"orange",
"outbox",
"outgoingcall",
"oxwall",
"pacman",
"pageback",
"pagebreak",
"pageforward",
"pagesetup",
"paintbrush",
"paintroll",
"palette-painting",
"paperclip",
"paperclipalt",
"paperclipvertical",
"paperplane",
"parentheses",
"parkeddomain",
"password",
"passwordalt",
"pasta",
"patch",
"path",
"pause",
"paw-pet",
"pawn",
"paypal",
"peace",
"pen",
"pencil",
"pepperoni",
"percent",
"perl-camel",
"perlalt",
"phone-call",
"phonealt",
"phonebook",
"phonebookalt",
"phonemic",
"phoneold",
"photoshop",
"php",
"phpbb",
"phppear",
"piano",
"picture",
"pictureframe",
"piggybank",
"pigpena",
"pigpenb",
"pigpenc",
"pigpend",
"pigpene",
"pigpenf",
"pigpeng",
"pigpenh",
"pigpeni",
"pigpenj",
"pigpenk",
"pigpenl",
"pigpenm",
"pigpenn",
"pigpeno",
"pigpenp",
"pigpenq",
"pigpenr",
"pigpens",
"pigpent",
"pigpenu",
"pigpenv",
"pigpenw",
"pigpenx",
"pigpeny",
"pigpenz",
"pilcrow",
"pill-antivirusalt",
"pin",
"pipe",
"piwigo",
"pizza",
"placeadd",
"placealt",
"placealtadd",
"placealtdelete",
"placedelete",
"placeios",
"plane",
"plaque",
"play",
"play-circle",
"playstore",
"playvideo",
"plug",
"pluginalt",
"plus",
"plus-sign",
"pocket",
"podcast",
"podium-winner",
"pokemon",
"police",
"polygonlasso",
"post",
"postalt",
"pound",
"poundalt",
"powerjack",
"powerplug",
"powerplugeu",
"powerplugus",
"presentation",
"prestashop",
"pretzel",
"preview",
"previous",
"print",
"protecteddirectory",
"pscircle",
"pscursor",
"psdown",
"psleft",
"pslone",
"psltwo",
"psright",
"psrone",
"psrtwo",
"pssquare",
"pstriangle",
"psup",
"psx",
"pull",
"punisher",
"push",
"puzzle-plugin",
"python",
"qrcode",
"quake",
"queen",
"query",
"question-sign",
"quote",
"quotedown",
"quoteup",
"raceflag",
"racquet",
"radio",
"radioactive",
"radiobutton",
"railroad",
"rain",
"ram",
"random",
"rar",
"raspberry",
"raspberrypi",
"rawaccesslogs",
"razor",
"reademail",
"record",
"rectangle",
"recycle",
"reddit",
"redirect",
"refresh",
"reliability",
"remote",
"remove",
"remove-circle",
"remove-sign",
"removefriend",
"repeat",
"repeatone",
"resellerhosting",
"residentevil",
"resistor",
"resize",
"resize-full",
"resize-horizontal",
"resize-small",
"resize-vertical",
"restart",
"restaurantmenu",
"restore",
"restricted",
"retweet",
"rim",
"ring",
"road",
"roadsign-roadsignright",
"roadsignleft",
"robocop",
"rocket-launch",
"rook",
"root",
"rorschach",
"rotateclockwise",
"rotatecounterclockwise",
"roundrectangle",
"route",
"router",
"rss",
"rubberstamp",
"ruby",
"ruler",
"sad",
"safetypin",
"satellite",
"satellitedish-remotemysql",
"save-floppy",
"scales",
"science-atom",
"scope-scan",
"scopealt",
"screenshot",
"screw",
"screwdriver",
"screwdriveralt",
"script",
"sd",
"search",
"searchdocument",
"searchfolder",
"security-shield",
"securityalt-shieldalt",
"selection-rectangleselection",
"selectionadd",
"selectionintersect",
"selectionremove",
"seo",
"server",
"servers",
"settingsandroid",
"settingsfour-gearsalt",
"settingsthree-gears",
"settingstwo-gearalt",
"shades-sunglasses",
"shapes",
"share",
"share-alt",
"sharealt",
"sharedfile",
"sharedhosting",
"sharethree",
"sheriff",
"shipping",
"shopping",
"shopping-cart",
"shoppingbag",
"shortcut",
"shovel",
"shredder",
"shutdown",
"sidebar",
"signal",
"sim",
"simalt",
"skrill",
"skull",
"skype",
"skypeaway",
"skypebusy",
"skypeoffline",
"skypeonline",
"smaller",
"smf",
"smile",
"snow",
"snowman",
"socialnetwork",
"software",
"sortbynameascending-atoz",
"sortbynamedescending-ztoa",
"sortbysizeascending",
"sortbysizedescending",
"soundwave",
"soup",
"spaceinvaders",
"spades",
"spam",
"spamalt",
"spawn",
"speaker",
"speed",
"spider",
"spiderman",
"split",
"spoon",
"spray",
"spreadsheet",
"squareapp",
"squarebrackets",
"ssh",
"sslmanager",
"stadium",
"stamp",
"stampalt",
"star",
"star-empty",
"starempty",
"starfull",
"starhalf",
"steak",
"steam",
"step-backward",
"step-forward",
"sticker",
"stiletto",
"stockdown",
"stocks",
"stockup",
"stomach",
"stop",
"stopwatch",
"storage-box",
"storagealt-drawer",
"store",
"storm",
"stove",
"strawberry",
"strikethrough",
"student-school",
"stumbleupon",
"subdomain",
"submarine",
"subscript",
"subtractshape",
"sum",
"sun-day",
"sunnysideup",
"superman",
"superscript",
"support",
"supportalt",
"switch",
"switchoff",
"switchoffalt",
"switchon",
"switchonalt",
"sword",
"sync",
"syncalt",
"synckeeplocal",
"synckeepserver",
"syringe-antivirus",
"tablet",
"tabletennis-pingpong",
"taco",
"tag",
"tagalt-pricealt",
"tags",
"tagvertical",
"tank",
"target",
"taskmanager-logprograms",
"tasks",
"taxi",
"tea",
"teapot",
"telescope",
"temperature-thermometer",
"temperaturealt-thermometeralt",
"tennis",
"tent-camping",
"terminal",
"tethering",
"tetrisone",
"tetristhree",
"tetristwo",
"text-height",
"text-width",
"th",
"th-large",
"th-list",
"theather",
"theme-style",
"thissideup",
"threecolumns",
"thumbs-down",
"thumbs-up",
"ticket",
"tictactoe",
"tie-business",
"time",
"timeline",
"tint",
"toast",
"toiletpaper",
"tooth",
"toothbrush",
"tophat",
"torigate",
"touchpad",
"trafficlight",
"transform",
"trash",
"trashempty",
"trashfull",
"travel",
"treediagram",
"treeornament",
"triangle",
"tron",
"trophy",
"truck",
"trumpet",
"tumblr",
"tv",
"twitter",
"twocolumnsleft",
"twocolumnsleftalt",
"twocolumnsright",
"twocolumnsrightalt",
"ubuntu",
"umbrella",
"underline",
"undo",
"unlock",
"upleft",
"upload",
"uploadalt",
"upright",
"uptime",
"usb",
"usbalt",
"usbplug",
"user",
"userfilter",
"usfootball",
"value-coins",
"vector",
"vendetta",
"video",
"viking",
"vimeo",
"vinyl",
"violin",
"virus",
"visa",
"visitor",
"vlc-cone",
"voice",
"volume-down",
"volume-off",
"volume-up",
"vps",
"wacom",
"walle",
"wallet",
"warcraft",
"warmedal",
"warning-sign",
"washer",
"watch",
"watertap-plumbing",
"wave-sea",
"wavealt-seaalt",
"webcam",
"webcamalt",
"webhostinghub",
"webmail",
"webpage",
"webplatform",
"websitealt",
"websitebuilder",
"weight",
"westernunion",
"wheel",
"wheelchair",
"whistle",
"whmcs",
"wifi",
"wind",
"windleft",
"windows",
"windright",
"wine",
"wizard",
"wizardalt",
"wizardhat",
"woman-female",
"women",
"wordpress",
"wrench",
"wrenchalt",
"xbox",
"xmen",
"yahoo",
"yen",
"yenalt",
"yinyang",
"youtube",
"zelda",
"zikula",
"zip",
"zodiac-aquarius",
"zodiac-aries",
"zodiac-cancer",
"zodiac-capricorn",
"zodiac-gemini",
"zodiac-leo",
"zodiac-libra",
"zodiac-pisces",
"zodiac-sagitarius",
"zodiac-scorpio",
"zodiac-taurus",
"zodiac-virgo",
"zoom-in",
"zoom-out",
"vk",
"bitcoin",
"rouble",
"phpnuke",
"modx",
"eoneohseven",
"subrion",
"typothree",
"tikiwiki",
"pligg",
"pyrocms",
"mambo",
"contao",
"crackedegg",
"coffeecupalt",
"reademailalt",
"train",
"shoebox",
"bathtub",
"ninegag",
"pebble",
"musicthree",
"stairsup",
"stairsdown",
"bookalt",
"programclose",
"programok",
"splitalt",
"solarsystem",
"honeycomb",
"tools",
"xoops",
"pixie",
"dotclear",
"impresscms",
"saurus",
"impresspages",
"monstra",
"snews",
"jcore",
"silverstripe",
"btwoevolution",
"nucleus",
"symphony",
"vanillacms",
"bbpress",
"phpbbalt",
"chyrp",
"pivotx",
"pagecookery",
"moviereelalt",
"cassettealt",
"photobucket",
"technorati",
"theverge",
"stacks",
"dotlist",
"numberlist",
"indentleft",
"indentright",
"fblike",
"fbdislike",
"sale",
"sharetronix",
"markerdown",
"markerup",
"markerleft",
"markerright",
"bookmarkalt",
"calendarthree",
"wineglass",
"slidersoff",
"slidersmiddle",
"slidersfull",
"slidersdesc",
"slidersasc",
"slideronefull",
"slidertwofull",
"sliderthreefull",
"noborders",
"bottomborder",
"topborder",
"leftborder",
"rightborder",
"horizontalborder",
"verticalborder",
"outerborders",
"innerborders",
"fullborders",
"networksignalalt",
"resizeverticalalt",
"resizehorizontalalt",
"moneyalt",
"fontcase",
"playstation",
"cube",
"sphere",
"ceilinglight",
"chandelier",
"details",
"detailsalt",
"bullet",
"gun",
"processorthree",
"world",
"statistics",
"shoppingcartalt",
"microphonealt",
"routeralt",
"shell",
"squareplay",
"squarestop",
"squarepause",
"squarerecord",
"squareforward",
"squareback",
"squarenext",
"squareprevious",
"mega",
"charliechaplin",
"popcorn",
"fatarrowright",
"fatarrowleft",
"fatarrowdown",
"fatarrowup",
"shirtbutton",
"shirtbuttonalt",
"cuckooclock",
"lens",
"voltage",
"planealt",
"busalt",
"lipstick",
"plantalt",
"paperboat",
"texture",
"dominoone",
"dominotwo",
"dominothree",
"dominofour",
"dominofive",
"dominosix",
"dominoseven",
"dominoeight",
"dominonine",
"connected",
"connectedpc",
"musicsheet",
"rdio",
"spotify",
"deviantart",
"yelp",
"behance",
"nfc",
"earbudsalt",
"earbuds",
"amazon",
"openid",
"digg",
"retweet",
"moonnew",
"moonwaxingcrescent",
"moonfirstquarter",
"moonwaxinggibbous",
"moonfull",
"moonwaninggibbous",
"moonthirdquarter",
"moonwaningcrescent",
"planet",
"sodacup",
"cocktail",
"church",
"mosque",
"comedy",
"tragedy",
"bacon",
"trailor",
"tshirt",
"design",
"spiderweb",
"fireplace",
"tallglass",
"grapes",
"biohazard",
"directions",
"equalizerthree",
"mountains",
"bing",
"windowseight",
"microsoftoffice",
"salealt",
"purse",
"chickenalt",
"podium",
"findfriends",
"microphonethree",
"workshirt",
"donotdisturb",
"addtags",
"removetags",
"carbattery",
"debug",
"trojan",
"molecule",
"safetygoggles",
"leather",
"teddybear",
"stroller",
"circleplay",
"circlestop",
"circlepause",
"circlerecord",
"circleforward",
"circlebackward",
"circlenext",
"circleprevious",
"circleplayempty",
"circlestopempty",
"circlepauseempty",
"circlerecordempty",
"circleforwardempty",
"circlebackwardempty",
"circlenextempty",
"circlepreviousempty",
"belt",
"bait",
"manalt",
"womanalt",
"clover",
"pacifier",
"calcplus",
"calcminus",
"calcmultiply",
"calcdivide",
"calcequals",
"city",
"hdvideo",
"horizontalexpand",
"horizontalcontract",
"radar",
"threed",
"flickralt",
"pattern",
"elevator",
"escalator",
"portrait",
"cigar",
"dropbox",
"origami",
"opensource",
"redaxscript",
"mahara",
"forkcms",
"pimcore",
"bigace",
"aef",
"punbb",
"phorum",
"fluxbb",
"minibb",
"zenphoto",
"fourimages",
"plogger",
"jcow",
"elgg",
"etano",
"openclassifieds",
"osclass",
"openx",
"phplist",
"roundcube",
"pommo",
"webinsta",
"limesurvey",
"fengoffice",
"eyeos",
"dotproject",
"collabtive",
"projectpier",
"taskfreak",
"eventum",
"traq",
"mantisbugtracker",
"oscommerce",
"zencart",
"tomatocart",
"boxbilling",
"zurmo",
"orangehrm",
"vtiger",
"mibew",
"phpmyfaq",
"yiiframework",
"zendframework",
"fuelphp",
"kohana",
"smarty",
"sidu",
"simplepie",
"projectsend",
"extjs",
"raphael",
"sizzle",
"yui",
"scissorsalt",
"cuthere",
"coinsalt",
"parkingmeter",
"treethree",
"packarchive",
"unpackarchive",
"terminalalt",
"jersey",
"vial",
"noteslist",
"notestasks",
"notesdate",
"noteslocation",
"noteslistalt",
"notestasksalt",
"notesdatealt",
"noteslocationalt",
"useralt",
"adduseralt",
"removeuseralt",
"banuseralt",
"banuser",
"paintrollalt",
"textcursor",
"textfield",
"precisecursor",
"brokenlink",
"bookmarkthree",
"bookmarkfour",
"warmedalalt",
"thinking",
"commentlove",
"commentsmiley",
"sharetwo",
"emptystar",
"halfstar",
"fullstar",
"forbidden",
"indentleftalt",
"indentrightalt",
"modxalt",
"apple",
"greekcolumn",
"walletalt",
"dollarsquare",
"poundsquare",
"yensquare",
"eurosquare",
"bitcoinsquare",
"roublesquare",
"roublealt",
"bitcoinalt",
"gavel",
"barchartasc",
"barchartdesc",
"house",
"garage",
"milk",
"hryvnia",
"hryvniasquare",
"hryvniaalt",
"beeralt",
"trolleyfull",
"trolleyload",
"trolleyunload",
"trolleyempty",
"mootools",
"mootoolstwo",
"mootoolsthree",
"mysqlthree",
"mysqlalt",
"pgsql",
"mongodb",
"neofourj",
"nosql",
"catface",
"polaroid",
"clouderror",
"camcorder",
"projector",
"sdvideo",
"fx",
"gramophone",
"speakeralt",
"hddalt",
"usbflash",
"manillaenvelope",
"stickynote",
"stickynotealt",
"torch",
"flashlightalt",
"campfire",
"cctv",
"drill",
"lampalt",
"flowerpot",
"defragment",
"panoramio",
"panorama",
"photosphere",
"panoramaalt",
"timer",
"burstmode",
"cameraflash",
"autoflash",
"noflash",
"threetofour",
"sixteentonine",
"cat",
"dog",
"rabbit",
"koala",
"butterflyalt",
"butterfly",
"wwf",
"poop",
"poopalt",
"kiwi",
"kiwifruit",
"lemon",
"pear",
"watermelon",
"onion",
"turnip",
"eggplant",
"avocado",
"perfume",
"arch",
"pluspages",
"community",
"pluscircles",
"googleplusold",
"plusgames",
"event",
"miui",
"hot",
"flowup",
"flowdown",
"moustache",
"angle",
"sleep",
"acorn",
"steamalt",
"resizeupleft",
"resizeupright",
"resizedownright",
"resizedownleft",
"hammeralt",
"bamboo",
"mypictures",
"mymusic",
"myvideos",
"systemfolder",
"bookthree",
"compile",
"report",
"fliphorizontal",
"flipvertical",
"construction",
"counteralt",
"counter",
"papercutter",
"snaptodot",
"snaptogrid",
"caligraphy",
"icecreamthree",
"skitch",
"archlinux",
"elementaryos",
"loadingone",
"loadingtwo",
"loadingthree",
"loadingfour",
"loadingfive",
"loadingsix",
"loadingseven",
"loadingeight",
"brokenheart",
"heartarrow",
"heartsparkle",
"cell",
"panda",
"refreshalt",
"mirror",
"headphonesthree",
"fan",
"tornado",
"hangout",
"beaker",
"beakeralt",
"phonescreensize",
"tabletscreensize",
"notification",
"googleglass",
"pinterest",
"soundcloud",
"alarmclock",
"addalarm",
"deletealarm",
"turnoffalarm",
"snooze",
"bringforward",
"sendbackward",
"bringtofront",
"sendtoback",
"tectile",
"grave",
"gravetwo",
"gravethree",
"gravefour",
"textlayer",
"vectoralt",
"drmanhattan",
"foursquarealt",
"hashtag",
"enteralt",
"exitalt",
"cartalt",
"vaultthree",
"fatundo",
"fatredo",
"feedly",
"feedlyalt",
"squareheart",
"squarestar",
"squarecomment",
"squarelike",
"squarebookmark",
"squaresearch",
"squaresettings",
"squarevoice",
"google",
"emojigrinalt",
"emojigrin",
"constellation",
"emojisurprise",
"emojidead",
"emojiangry",
"emojidevil",
"emojiwink",
"moonorbit",
"emojismile",
"emojisorry",
"emojiconfused",
"emojisleep",
"emojicry",
"circlefork",
"circlespoon",
"circleknife",
"circlepencil",
"circlehammer",
"circlescrewdriver",
"middlefinger",
"heavymetal",
"turnright",
"turnleft",
"vineapp",
"vineappalt",
"finance",
"survey",
"hangouts",
"square0",
"square1",
"square2",
"square3",
"square4",
"square5",
"square6",
"square7",
"square8",
"square9",
"squarea",
"squareb",
"squarec",
"squared",
"squaree",
"squaref",
"squareg",
"squareh",
"squarei",
"squarej",
"squarek",
"squarel",
"squarem",
"squaren",
"squareo",
"squarep",
"squareq",
"squarer",
"squares",
"squaret",
"squareu",
"squarev",
"squarew",
"squarex",
"squarey",
"squarez",
"shuttle",
"meteor",
"galaxy",
"observatory",
"astronaut",
"asteroid",
"sunrise",
"sunset",
"tiderise",
"tidefall",
"mushroomcloud",
"galaxyalt",
"sputnik",
"sextant",
"spock",
"meteorite",
"deathstar",
"deathstarbulding",
"fallingstar",
"windmill",
"windmillalt",
"pumpjack",
"nuclearplant",
"solarpanel",
"barrel",
"canister",
"railtunnel",
"roadtunnel",
"pickaxe",
"cow",
"sheep",
"fountain",
"circlezero",
"circleone",
"circletwo",
"circlethree",
"circlefour",
"circlefive",
"circlesix",
"circleseven",
"circleeight",
"circlenine",
"circlea",
"circleb",
"circlec",
"circled",
"circlee",
"circlef",
"circleg",
"circleh",
"circlei",
"circlej",
"circlek",
"circlel",
"circlem",
"circlen",
"circleo",
"circlep",
"circleq",
"circler",
"circles",
"circlet",
"circleu",
"circlev",
"circlew",
"circlex",
"circley",
"circlez",
"creeper",
"minecraft",
"minecraftalt",
"pixelsword",
"pixelbroadsword",
"pixelwand",
"pixelpotion",
"pixelpotionalt",
"pixelpickaxe",
"pixelbow",
"pixelarrow",
"pixelaxe",
"pixeldagger",
"pixelbastardsword",
"pixellance",
"pixelbattleaxe",
"pixelshovel",
"pixelsphere",
"pixelelixir",
"pixelchest",
"pixelshield",
"pixelheart",
"rudder",
"folderalt",
"removefolderalt",
"addfolderalt",
"deletefolderalt",
"openfolderalt",
"clipboardalt",
"pastealt",
"loadingflowccw",
"loadingflowcw",
"code",
"cloveralt",
"lips",
"kiss",
"manualshift",
"simcardthree",
"parthenon",
"addcomment",
"deletecomment",
"gender",
"callalt",
"outgoingcallalt",
"incomingcallalt",
"missedcallalt",
"export",
"import",
"cherryalt",
"panties",
"kimai",
"livejournal",
"livejournalalt",
"tagged",
"temple",
"mayanpyramid",
"egyptpyramid",
"tampermonkey",
"pushbullet",
"currents",
"communitysmall",
"squaregithub",
"projectfork",
"projectmerge",
"projectcompare",
"history",
"notebook",
"issue",
"issueclosed",
"issuereopened",
"rubyalt",
"lighton",
"lightoff",
"bellalt",
"versions",
"twog",
"threeg",
"fourg",
"gpsalt",
"circleloaderfull",
"circleloaderseven",
"circleloadersix",
"circleloaderfive",
"circleloaderfour",
"circleloaderthree",
"circleloadertwo",
"circleloaderone",
"circleloaderempty",
"whatsapp",
"whatsappalt",
"viber",
"squareviber",
"teamviewer",
"tunein",
"tuneinalt",
"weightscale",
"boxing",
"speedalt",
"scriptalt",
"splitthree",
"mergethree",
"layersthree",
"mutemic",
"zerply",
"circlegoogleplus",
"circletwitter",
"circlefacebook",
"circleyahoo",
"circlegithub",
"forumsalt",
"circlepath",
"circlevimeo",
"circlevine",
"instagramtwo",
"instagramthree",
"flickrthree",
"quora",
"squarequora",
"circlequora",
"picasa",
"branch",
"ingress",
"squarezerply",
"circlezerply",
"squarevimeo",
"squaretwitter",
"brightnessalt",
"brightnessalthalf",
"brightnessaltfull",
"brightnessaltauto",
"shirtbuttonthree",
"openshare",
"copyapp",
"bowl",
"cloudalt",
"cloudaltdownload",
"cloudaltupload",
"cloudaltsync",
"cloudaltprivate",
"flipboard",
"octoloaderempty",
"octoloaderone",
"octoloadertwo",
"octoloaderthree",
"octoloaderfour",
"octoloaderfive",
"octoloadersix",
"octoloaderseven",
"octoloaderfull",
"selectionsymbol",
"infinityalt",
"pullrequest",
"projectforkdelete",
"projectforkprivate",
"commit",
"htmlfile",
"pushalt",
"pullalt",
"photonineframes",
"wetfloor",
"instagramfour",
"circleinstagram",
"videocamerathree",
"subtitles",
"subtitlesoff",
"compress",
"baby",
"ducky",
"handswipe",
"swipeup",
"swipedown",
"twofingerswipedown",
"twofingerswipeup",
"doubletap",
"dribbblealt",
"circlecallmissed",
"circlecallincoming",
"circlecalloutgoing",
"circledownload",
"circleupload",
"minismile",
"minisad",
"minilaugh",
"minigrin",
"miniangry",
"minitongue",
"minitonguealt",
"miniwink",
"minitonguewink",
"miniconfused",
"soundright",
"soundleft",
"savetodrive",
"layerorderup",
"layerorderdown",
"layerorder",
"circledribbble",
"squaredribbble",
"handexpand",
"handpinch",
"fontserif",
"fontsansserif",
"fontrounded",
"fonthandwriting",
"fonttypewriter",
"fontcomic",
"fontcaligraphy",
"fontgothic",
"fontstencil"];
    
    
    return factory;
    
}); //end synonymService.factory()